FROM python:3.9.1-buster as base

MAINTAINER Courtel Eliot <eliot.courtel@wanadoo.fr>
WORKDIR /home/api

FROM base as prod

COPY ./back/sso/src/requirements.txt ./
RUN pip3 install --upgrade -r requirements.txt

ENTRYPOINT python3 server.py;
